### ISSUE TITLE
Seção 15: React - Redux - Redux Saga - React Hooks e componentes funcionais - Avançado

### ISSUE THREAD

**Issue by VictorCastro22** [VictorCastro22/IFCE_JS_VICTORMANUEL#15]
- [ ] Modificações na API Rest
- [ ] Eslint, prettier e editorconfig
- [ ] Limpando o projeto
- [ ] Styled-Components
- [ ] Configurando as cores
- [ ] Menu da aplicação
- [ ] Aviso importante
- [ ] React Router DOM
- [ ] Router e History
- [ ] Corrigindo a versão do history
- [ ] MyRoute - Rota personalizada e privada
- [ ] React Toastify
- [ ] Configurando o Axios
- [ ] Redux + React
- [ ] Separando Actions e Reducers
- [ ] Redux Saga
- [ ] Redux Persist
- [ ] Copiando a base para o projeto
- [ ] Páginas e rotas da aplicação
- [ ] Buscando alunos da API
- [ ] Cadastrando novos usuários na aplicação
- [ ] Login #1
- [ ] Login #2
- [ ] Componente Loading
- [ ] Edição dos dados do usuário logado #1 
- [ ] Edição dos dados do usuário logado #2
- [ ] Logout
- [ ] Excluindo alunos
- [ ] Corrigindo o LOGIN_FAILURE
- [ ] Cadastro de alunos #1
- [ ] Cadastro de alunos #2
- [ ] Cadastro de alunos #3
- [ ] Exibindo a foto do aluno
- [ ] Editando a foto do aluno
- [ ] Deploy do React com NGINX
