### ISSUE TITLE
Seção 25: TypeScript - Princípios SOLID (S.O.L.I.D)

### ISSUE THREAD

**Issue by VictorCastro22** [VictorCastro22/IFCE_JS_VICTORMANUEL#25]
- [ ] O que são os princípios S.O.L.I.D. (SOLID)
- [ ] Configurando um novo projeto
- [ ] Github da seção
- [ ] Criando um carrinho de compras (sem princípios)
- [ ] SRP - Single Responsibility Principle (Princípio da responsabilidade única)
- [ ] OCP - Open/Closed Principle (Princípio do aberto/fechado) #1
- [ ] OCP - Open/Closed Principle (Princípio do aberto/fechado) #2 
- [ ] LSP - Liskov Substitution Principle (Princípio da Substituição de Liskov)
- [ ] ISP - Interface Segregation Principle (Princípio da Segregação de Interface) #1 
- [ ] ISP - Interface Segregation Principle (Princípio da Segregação de Interface) #2 
- [ ] DIP - Dependency Inversion Principle (Princípio da Inversão de Dependência)
- [ ] Vantagens, desvantagens e DRY, YAGNI, KISS, SOC, MVP
